export { default as H1 } from './H1'
// export { default as H2 } from './H2'
// export { default as H3 } from './H3'
// export { default as H4 } from './H4'
// export { default as ReadMoreText } from './ReadMoreText'
export { default as Link } from './Link'
export { default as Text } from './Text'
// export { default as P } from './P'
// export { default as SmallText } from './SmallText'
export { default as TextBase } from './TextBase'

// export { LINK_VARIANT } from './Link'
